### ISSUE TITLE
New values: Losses, weighted Kills, per player kills, Weighted current units

### ISSUE THREAD

**Issue by GRhin** [patel-nikhil/SHCLiveStatReader#3]
![image](https://user-images.githubusercontent.com/46951246/74587035-c667a900-5041-11ea-88c0-41b3a1c4f692.png)

For the most part this was extrapolation, so not 100% on all these values. 
Id love Current Weighted Units to be sent with the other current stats. And the weighted kills/losses would be interesting in the after-game stats.
Summing Kills vs Player Y would give total kills, and that would be nice to send to current stats with total losses (to display a k/d)

EDIT: update img to underline numbers i can guarantee
EDIT 2: all player kills x is off. weirdness happening

**Comment by ghost** [comment]
Can you specify the version you use?

**Comment by GRhin** [comment]
1.41E with UCP 2.13 installed.
All values so far implemented are this version.
Note the "E" - these are all for Extreme (play regular maps, with magic bar disabled, just like higher unit limit in extreme)

EDIT: Combining messages

If you are wanting to get the values for regular crusader, you should be able to just get the first column, and add the "difference" column to predict the rest of the values.

**Comment by GRhin** [comment]
If you are wanting to get the values for regular crusader, you should be able to just get the first column, and add the "difference" column to predict the rest of the values.

**Comment by GRhin** [comment]
OK, further investigation, I have confirmed enough of the rows including "kills Against Player 1"  "kills Against Player 2"  "kills Against Player 3" to be reasonably confident on those addresses. however the rows below that I am not confident of.

**Comment by ghost** [comment]
Are the addresses the same in multiplayer?
Also, is there any way to find out if a player is still alive or not?

**Comment by GRhin** [comment]
Yes same for multiplayer. 
You know if a player is alive or not by checking his available population (housing?) as the keep provides 10, so if they are alive you get at least 10, but if they are dead its 0.
But thats another issue.

**Comment by GRhin** [comment]
DAMNIT!!! 
So i was testing with a second computer playing. first P1 vs P2, then P1 vs P3, now P2 vs P3. unfortunately, while one value is matching the address of P1 vs P2 :(

**Comment by ghost** [comment]
I'm also searching for addresses right now, but the distance interval of 14836 doesn't seem to work always...

Do you have a table for the other values (population etc.)?

**Comment by GRhin** [comment]
OK, lots of posts, im sorry. I think i got it this time. Pretty sure row 2 of the "kills vs x" in the original screenshot doesnt exist, except as "current player kills x". 
Pretty sure first row is the "losses row" and (now) second row is the "kills" row (i.e first row belongs to the player in the row title, second row belongs to the player in the column title)

@void4 14836 is not an address, its the number of bytes between locations (pretty sure its number of bytes between players storage location)
Search the Hexadecimal addresses with white backgrounds :) And test the following image.

![image](https://user-images.githubusercontent.com/46951246/74588644-60cfe880-5052-11ea-867d-6a4f3399f06e.png)

**Comment by ghost** [comment]
What tool do you use for searching? Last time I used CheatEngine, this time I wrote something myself (search.py in https://github.com/void4/PySHCLiveReader)

**Comment by GRhin** [comment]
yea im using CheatEngine to find addresses not implemented into the Stat Reader.

**Comment by GRhin** [comment]
OK that last screen shot has been correct for every value ive checked, I even loaded a 8 player game going nuts at max speed to ensure values were populating correctly. Im 90% certain all addresses in that table are correct

https://docs.google.com/spreadsheets/d/1Bwee7Fdf4RXY-mQPhrU451nTrNdrmbRtUWGkUMprPgA/edit?usp=sharing

**Comment by patel-nikhil** [comment]
Commit 5e8aee4 adds the current weighted units. PR #7 adds weighted troops killed.

The game doesn't appear to sum and store the unweighted total troops killed, and it's not currently used in the greatest lord calculation, so I'll be holding off on adding that until I decide the extent to which I want to implement 'category' sums
