### ISSUE TITLE
working out after-game stats screen

### ISSUE THREAD

**Issue by GRhin** [patel-nikhil/SHCLiveStatReader#4]
So, we have noticed that the after-game stats are all located around the same area, so to facilitate finding these stats. i have made a spreadsheet containing all adress locations around the area of the stats we have already found. and labeled the addresses we know (and bolded)

https://docs.google.com/spreadsheets/d/1Pg_LMhhTN82vhezguDuMJTtXuZGSOAAXtZyzpfY7SIw/edit?usp=sharing

Note that the odd-number player names are off by 2 bytes.
There are some convenient gaps that could include pitch, total kills, score, or something similar. If you want to check out addresses, or know where some are, let me know and i can update it.

**Comment by ghost** [comment]
The creator of http://statsmylord.com/ (@lawrencefoley, also on the Sourcehold Discord) may have more information on the structure.

Somewhere in there should be the "death" skull 
![image](https://user-images.githubusercontent.com/11392207/74606756-50138700-50d3-11ea-863a-2ec42e9941f1.png)

**Comment by GRhin** [comment]
Thats great, at this stage i think we have found everything he has, plus a bit more. I think we have even found the death time/date...
One of the big things i want to find is the "score" the thing that defines the order of greatest lord... I think i know the adress by looking at this sheet, but havent had a chance to look yet.

**Comment by lawrencefoley** [comment]
This is a really cool project! Awesome to see someone working on something similar to my website. Looks like you have all the stats that I have on my website, but I would be more than happy to share my findings or code. It's a bit of a mess right now so I'd like to clean it up before putting it on a public repo, but I could share pieces of it if that would help.

As for the "score" value, I had looked for that a while myself. I'll let you know here if I find it before the rest of the group does.

Also, would it be ok if I used the memory addresses the group find in my website? @patel-nikhil 

Edit: I've attached my config file. This is for versions 1.4 and 1.4.1 of the SHC.
[config.zip](https://github.com/patel-nikhil/SHCLiveStatReader/files/4210807/config.zip)

**Comment by patel-nikhil** [comment]
@lawrencefoley I just opened your website - very nicely done!

My codebase is still in very early stages, and now that I know with help from @GRhin more information regarding offset between player stats, etc. I plan to revise make my logic more modular and efficient.

@GRhin has been helping me significantly with finding the memory values, and barring any objections from him, of course, I'm more than happy to let you use it on your website

**Comment by GRhin** [comment]
@lawrencefoley thanks for the zip, will browse soon. 
I hadnt seen your project before void pointed it out, and I like the idea.
I actually have a different application of the same idea on the backburner (much more complex, but what you have would be a part of it). If you are willing to share info when i get into it properly, add me on discord GRhin#9114 and ill explain the details of my application

Also, did you know about the weighted kills/deaths? They are much more informative when comparing players. I.e. 100 slaves lost is weighted to 100, but 100 E.archer gets weighted to 500, i have a list somewhere of the values of each unit, except for seige equipment and tunnelors which arent recorded. Ping my on discord if you want it.

And as another point, do you know how the stars in the after-game screen are calculated? a friend has been trying to work out a pattern to see how it decides to give 5 stars, or 2 or 11, and hasnt come up with anything.

**Comment by ghost** [comment]
@lawrencefoley I had a look at your `config.json`, can you explain what the "ID" field represents?
Also, do you generate the .json file from a table? Or do you edit it manually? In my MemoryReader, I use a more compact table format: https://github.com/void4/PySHCLiveReader/blob/master/tables.py

@GRhin In your Google Doc, you have many "P1 Kills P1", "P1 Kills P2" etc. fields. Are these unit kills?

**Comment by GRhin** [comment]
Good news, I have found today: 
-Players present in game (557-55E)
-Time at which players died (5A4-5C0)
-Gaia kills player x (5A4-5C0)
-# of Lords killed by player x (7EA-7F1)
-Weighted Buildings Destroyed (864-880)

**Comment by ghost** [comment]
Are the addresses the same if UCP is *not* installed?
Edit: Have you found a way to make the game not fullscreen?

**Comment by GRhin** [comment]
I think so, but cannot be 100% certain as I have not checked

**Comment by lawrencefoley** [comment]
> @lawrencefoley thanks for the zip, will browse soon.
> I hadnt seen your project before void pointed it out, and I like the idea.
> I actually have a different application of the same idea on the backburner (much more complex, but what you have would be a part of it). If you are willing to share info when i get into it properly, add me on discord GRhin#9114 and ill explain the details of my application
> 
> Also, did you know about the weighted kills/deaths? They are much more informative when comparing players. I.e. 100 slaves lost is weighted to 100, but 100 E.archer gets weighted to 500, i have a list somewhere of the values of each unit, except for seige equipment and tunnelors which arent recorded. Ping my on discord if you want it.
> 
> And as another point, do you know how the stars in the after-game screen are calculated? a friend has been trying to work out a pattern to see how it decides to give 5 stars, or 2 or 11, and hasnt come up with anything.

@GRhin 
I'll DM you on Discord. I haven't found where the weighted kills are. I'd love to know though. :-)

@void4 
Oh, the ID field doesn't mean anything. I generate that JSON file from a CheatEngine file so that ID just corresponds to the ID in the CheatEngine file I have. I prefer the JSON format because it's more structured, but I'd be open to working on a different format together.

Also, more of a general question: What version of the game are you guys using? I'm using the 1.4 and 1.4.1 version of the Steam game.

**Comment by GRhin** [comment]
This is 1.41E, I use extreme when i stream for the extra unit limit, but without magic bar and outposts etc. And that's where i am displaying these stats (over the game for viewers)
I'm guessing you *should* be able to use one of the values you already know, and find the rest with offsets. Ie. If you have total buildings destroyed, and we have weighted kills 32 bytes away from that, you can move 32 bytes away from your memory location to find it. Note that 32 was just a random number, not sure the actual offset

> 
> @GRhin In your Google Doc, you have many "P1 Kills P1", "P1 Kills P2" etc. fields. Are these unit kills?

Yes. It is how many units each player has killed from each enemy

**Comment by lawrencefoley** [comment]
@GRhin That makes sense. I used that same offset method when finding the values for different versions of the game.

**Comment by lawrencefoley** [comment]
For the "score" value that determines the greatest lord; Isn't this based on kills and gold? Wasn't sure if it is affected by other things in the game.

**Comment by GRhin** [comment]
Nikhil is testing now to see what effects it. i can tell you that already he has found that gold and weighted buildings destroyed effects it. and resources dont effect it.

**Comment by patel-nikhil** [comment]
I've now added the greatest lord score calculation to my program. This is the greatest lord score for when the game has ended - greatest lord is calculated differently while the game is in progress.

The score is calculated based on the following factors:
- Gold (this value gets scaled and used)
- Weighted troops killed (gets added to score)
- Weighted buildings destroyed (multiplied by 100 and added to score)
- Acts as multiplier to the gold, weighted troops, weighted buildings values
- Number of in-game months the game lasted

The following is the calculation the game uses to calculate greatest lord score.
Note A >> B is shift right, (also I believe, equal to integer division by 2), repeated B times

            const long multiplier = 0x66666667;
            long goldBonus = ((gold * multiplier) >> 32) / 4;
            long score = goldBonus + weightedKills + weightedBuildings * 100;
            score = score + (score * lordKills) / 4;
            Int32 dateBonus = (endYear - startYear) * 12;
            dateBonus -= startMonth;
            dateBonus += endMonth;

            if (dateBonus < 1)
            {
                dateBonus = 1;
            }
            Int32 bonusDivider = 200 + dateBonus;

            score = score * 200;
            score = score / bonusDivider;
            return score;



Here is a [Python function](https://pastebin.com/vMABrmF0) I wrote that calculates the score. Not the cleanest, but I chose to write it that way as that was how it was done in disassembly. Also, I chose to hard code start year and month in my Python function for convenience; in practice my program reads all the values as they are stored in game.

**Comment by GRhin** [comment]
What is the multiplier? Looks like an address?
Does the lordsKilled divisor change defendant on the number of players?

**Comment by patel-nikhil** [comment]
Multiplier is a fixed value in hexadecimal.
The divide by 4s are actually shift arithmetic right (sar) 2 in the dissassembly -> also fixed
The divider of 200 also appears to be fixed.

Calculation runs for each player and I didn't see any of those values changed in-between, so not dependent on other factors from what I saw

I'm pretty sure some of my test scenarios had different numbers of players, I'll go back and test again when I have time.

**Comment by GRhin** [comment]
What is that fixed value?

**Comment by patel-nikhil** [comment]
The fixed value is the one I use in the function. So 0x66666667 is the multiplier for gold.
ie. the dissassembly does: mov eax, 0x66666667 and then imul (multiply) ecx

By fixed value I mean to say it's not loaded from another memory address. It's part of the instruction.

**Comment by GRhin** [comment]
But that is an address right? What is stored at that address? If it's an
equation then it amounts to 0 as 0 x anything is 0, which wouldn't work. So
it must be a pointer.

**Comment by patel-nikhil** [comment]
No, 0x66666667 is the number, as shown in the image, not the address of another number. 0x just means it's a hexadecimal number. And ecx register contains the total gold produced

![image](https://user-images.githubusercontent.com/12703092/75209187-a889fa80-574b-11ea-8bae-7e0ec5cbc4a1.png)

**Comment by GRhin** [comment]
That's a massive multiplier. Can you tell me what (multiplier >> 32) equates to? As that is the effective multiplier...

**Comment by patel-nikhil** [comment]
multiplier >> 32 is equivalent to multiplier / 2^32

**Comment by GRhin** [comment]
Yea I meant the decimal result of that, all good will do soon when I have the opportunity

**Comment by patel-nikhil** [comment]
Comes out to 0.4

**Comment by GRhin** [comment]
Then divided by 4, so its effectively
Gold bonus = gold/10

**Comment by patel-nikhil** [comment]
Yea that seems to be it.
I never thought to compute the decimal value, just followed the same logic and calculation, using the hex values to remove any room for error

**Comment by GRhin** [comment]
I think we have found everything here that we are going to.... so will close ticket.
